global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus сам себе
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Matrix AI Bot метрики
  - job_name: 'matrix-bot'
    static_configs:
      - targets: ['matrix-bot:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis метрики (якщо увімкнений redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node.js метрики
  - job_name: 'nodejs'
    static_configs:
      - targets: ['matrix-bot:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s 